<?php
/**
 * Copyright © 2016 by Mobivi.
 * Created by Long Nguyen.
 * User: longnguyen
 * Date: 28/09/2016
 * Time: 10:05
 */

namespace Icare\Sales\Controller\Adminhtml\Order\Edit;


use Magento\Framework\App\ObjectManager;

class Save extends \Magento\Sales\Controller\Adminhtml\Order\Edit\Save{
    /**
     * Dispatch request
     *
     * @return \Magento\Framework\Controller\ResultInterface|ResponseInterface
     * @throws \Magento\Framework\Exception\NotFoundException
     */
    public function execute() {
        $data = $this->getRequest()->getPost('order');
        if($data && isset($data['saving_account'])){
            $om = ObjectManager::getInstance();
            /**@var \Icare\Sales\Block\Adminhtml\Order\Create\SavingAccount $saBlock **/
            $saBlock = $om->get('Icare\Sales\Block\Adminhtml\Order\Create\SavingAccount');
            $account = $saBlock->getSavingAccount();
            $used = $saBlock->getDbSavingAccount();
            if(empty($account) || $data['saving_account_amount'] > $account->summary->accountBalance + $used['amount']) {
                $this->messageManager->addError(__('Invalid saving amount. Please check account balance information'));
                /** \Magento\Backend\Model\View\Result\Redirect $resultRedirect */
                $resultRedirect = $this->resultRedirectFactory->create();
                $resultRedirect->setPath('sales/*/');
                return $resultRedirect;
            }

        }
        return parent::execute();
    }

    /**
     * _processActionData
     * @param null $action
     * @return $this
     */
    public function _processActionData($action = NULL) {
        $result =  parent::_processActionData($action); // TODO: Change the autogenerated stub
        $data = $this->getRequest()->getPost('order');
        if(isset($data['saving_account'])){
            $this->_getOrderCreateModel()->getQuote()->setData('saving_account',1);
            $this->_getOrderCreateModel()->getQuote()->setData('saving_account_amount',$data['saving_account_amount']);
        }
        else{
            $this->_getOrderCreateModel()->getQuote()->setData('saving_account',0);
            $this->_getOrderCreateModel()->getQuote()->setData('saving_account_amount',0);
        }
        if(isset($data['auto_confirmation'])){
            $this->_getOrderCreateModel()->getQuote()->setData('auto_confirmation',true);
        }

        return $result;
    }
}