<?php
/**
 * Copyright © 2016 by Mobivi.
 * Created by Long Nguyen.
 * User: longnguyen
 * Date: 19/10/2016
 * Time: 17:45
 */

namespace Icare\Custom\Model;


use Magento\Framework\App\ObjectManager;

class Url extends \Magento\Backend\Model\Url{

    private $_authSession;
    /**
     * @var \Icare\Custom\Helper\ICareHelper $helper
     */
    private $helper;
    public function __construct(
        \Magento\Framework\App\Route\ConfigInterface $routeConfig,
        \Magento\Framework\App\RequestInterface $request,
        \Magento\Framework\Url\SecurityInfoInterface $urlSecurityInfo,
        \Magento\Framework\Url\ScopeResolverInterface $scopeResolver,
        \Magento\Framework\Session\Generic $session,
        \Magento\Framework\Session\SidResolverInterface $sidResolver,
        \Magento\Framework\Url\RouteParamsResolverFactory $routeParamsResolverFactory,
        \Magento\Framework\Url\QueryParamsResolverInterface $queryParamsResolver,
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        $scopeType,
        \Magento\Backend\Helper\Data $backendHelper,
        \Magento\Backend\Model\Menu\Config $menuConfig,
        \Magento\Framework\App\CacheInterface $cache,
        \Magento\Backend\Model\Auth\Session $authSession,
        \Magento\Framework\Encryption\EncryptorInterface $encryptor,
        \Magento\Store\Model\StoreFactory $storeFactory,
        \Magento\Framework\Data\Form\FormKey $formKey,
        array $data = []
    ) {
        $this->_authSession = $authSession;
        parent::__construct($routeConfig, $request, $urlSecurityInfo, $scopeResolver, $session, $sidResolver, $routeParamsResolverFactory, $queryParamsResolver, $scopeConfig, $scopeType, $backendHelper, $menuConfig, $cache, $authSession, $encryptor, $storeFactory, $formKey, $data);
    }

    public function getUrl($routePath = NULL, $routeParams = NULL) {
        if($routeParams == NULL) $routeParams = [];
        $user = $this->_authSession->getUser();
        $store_id = null;
        /**@var \Icare\Custom\Helper\ICareHelper $helper **/
        $helper =  ObjectManager::getInstance()->get('\Icare\Custom\Helper\ICareHelper');
        /**@var \Magento\Store\Model\StoreManager $storeManager **/
        $storeManager = ObjectManager::getInstance()->get('Magento\Store\Model\StoreManager');
        if($user){
            if (!$helper->checkSpecialUser($user) && !$storeManager->isSingleStoreMode()) {
                $store_id = $user->getStoreId();
            }
        }
        if($store_id != null)
            $routeParams['store'] = $store_id;
        return parent::getUrl($routePath, $routeParams); // TODO: Change the autogenerated stub
    }
}