<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magebuzz\Helpdesk\Block\Adminhtml\Ticket\Edit\Tab\General\Main\ListActions
 */
?>
<div class="actions">
<!--    <a class="action block-customer" href="--><?php //echo $block->_getBlockCustomerUrl(); ?><!--">-->
<!--        <span class="button">--><?php //echo __('Block This Customer') ?><!--</span>-->
<!--    </a>-->
<!--    <a class="action watch-ticket" href="--><?php //echo $block->_getWatchTicketUrl(); ?><!--">-->
<!--        <span class="button">--><?php //echo $block->_getWatchTicketLabel(); ?><!--</span>-->
<!--    </a>-->
</div>