<?php
/**
 * Copyright © 2016 by Mobivi.
 * Created by Long Nguyen.
 * User: longnguyen
 * Date: 25/10/2016
 * Time: 13:49
 */

namespace Icare\Custom\Block\Adminhtml;


class IcareSysNotification extends \Magento\AdminNotification\Block\System\Messages{
    private $_authSession;
    public $_template = '';
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\AdminNotification\Model\ResourceModel\System\Message\Collection\Synchronized $messages,
        \Magento\Framework\Json\Helper\Data $jsonHelper,
        array $data = [],
        \Magento\Backend\Model\Auth\Session $authSession
) {

        parent::__construct($context, $messages, $jsonHelper, $data);
        $this->_authSession = $authSession;
        //$this->setTemplate('Icare_Custom::system/message.phtml');
    }


    public function allowMessage() {
        $roles = $this->_authSession->getUser()->getRole()->getData();
        return (isset($roles['role_name']) && $roles['role_name'] == 'Administrators');
    }

    public function _toHtml() {
        if($this->allowMessage())
            return parent::_toHtml(); // TODO: Change the autogenerated stub
        return null;
    }
}