<?php
/**
 * Copyright © 2016 by Mobivi.
 * Created by Long Nguyen.
 * User: longnguyen
 * Date: 04/10/2016
 * Time: 11:58
 */
?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Receivable Histories') ?></span>
    </div>
    <div class="admin__page-section-content">
        <?=$block->getChildHtml('icare_deposit_receivable_list')?>
    </div>
</section>
