<?php
/**
 * Copyright © 2016 by Mobivi.
 * Created by Long Nguyen.
 * User: longnguyen
 * Date: 29/09/2016
 * Time: 15:57
 */

namespace Icare\Catalog\Block\Adminhtml\Product\Edit\Tab;


use Magento\Framework\App\ObjectManager;

class Websites extends \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Websites {
    /**
     *
     * @var \Icare\User\Helper\Role
     */
    protected $_roleHelper;

    /**
     *
     * @var \Icare\User\Helper\Role
     */
    protected $_authSession;

    /**
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Store\Model\WebsiteFactory $websiteFactory
     * @param \Magento\Store\Model\GroupFactory $storeGroupFactory
     * @param \Magento\Store\Model\StoreFactory $storeFactory
     * @param \Magento\Framework\Registry $coreRegistry
     * @param \Icare\User\Helper\Role $roleHelper,
     * @param \Magento\Backend\Model\Auth\Session $authSession
     * @param array $data
     */
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Store\Model\WebsiteFactory $websiteFactory,
        \Magento\Store\Model\GroupFactory $storeGroupFactory,
        \Magento\Store\Model\StoreFactory $storeFactory,
        \Magento\Framework\Registry $coreRegistry,
        \Icare\User\Helper\Role $roleHelper,
        \Magento\Backend\Model\Auth\Session $authSession,
        array $data = []
    ) {
        $this->_authSession = $authSession;
        $this->_roleHelper = $roleHelper;
        parent::__construct($context, $websiteFactory, $storeGroupFactory, $storeFactory, $coreRegistry, $data);
    }

    public function _construct() {
        $this->setTemplate('Icare_Catalog::catalog/product/edit/websites.phtml');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    public function getWebsiteCollection() {
        return parent::getWebsiteCollection();
    }

    public function getCurrentWebsiteId(){
        /** @var \Icare\Catalog\Block\Adminhtml\Product\Edit\Tab\Installments $installmentBlock */
        $installmentBlock = ObjectManager::getInstance()->get('Icare\Catalog\Block\Adminhtml\Product\Edit\Tab\Installments');
        $store_id = $installmentBlock->getCurrentStoreId();
        if($store_id){
            $store = $installmentBlock->getCurrentStore();
            $websiteId = $store->getWebsiteId();
            if ($websiteId !== null) {
               return $websiteId;
            }
        }else{
            return false;
        }
    }

    public function isSpecialUser() {
        $user = $this->_authSession->getUser();
        return $this->_roleHelper->checkSpecialUser($user);
    }
}