<?php
/**
 * Copyright © 2016 by Mobivi.
 * Created by Long Nguyen.
 * User: longnguyen
 * Date: 07/10/2016
 * Time: 09:28
 */

namespace Icare\Sales\Block\Adminhtml\Order\Create;


use Magento\Backend\Block\Template;
use Magento\Backend\Block\Widget;
use Magento\Framework\View\Element\AbstractBlock;
use Magento\Backend\Model\Auth\Session;
class AutoConfirmation extends Widget{

    protected $_template = 'Icare_Sales::order/create/totals/autoconfirmation.phtml';
    /**
     * @var \Magento\Backend\Model\Auth\Session
     */
    private $session;
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        array $data,
        Session $session

    ) {
        parent::__construct($context, $data);
        $this->session = $session;
    }

    public function _beforeToHtml() {

        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }

    public function canAutoConfirm(){
        $autoConfirm = 0;
        $user = $this->session->getUser();
        if($user->getData('is_allowed_confirm_order') == 1){
            $autoConfirm = $user->getData('is_allowed_confirm_order');
        }
        $store_id = $user->getStoreId();
        $om = \Magento\Framework\App\ObjectManager::getInstance();
        $storeObject = $om->get('\Magento\Store\Model\Store');
        $store = $storeObject->load($store_id);
        if($store->getData('store_is_autoconfirm') == 1){
            $autoConfirm = $store->getData('store_is_autoconfirm');
        }
        return $autoConfirm;
    }
}