<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div id="order_history_block" class="edit-order-comments">
 

    <ul class="note-list">
        <?php foreach ($block->getOrder()->getStatusHistoryCollection(true) as $_item): ?>
            <li class="note-list-item">
                <span class="note-list-date"><?php /* @escapeNotVerified */
                    echo $block->formatDate($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                <span class="note-list-time"><?php /* @escapeNotVerified */
                    echo $block->formatTime($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                <span class="note-list-status"><?php /* @escapeNotVerified */
                    echo $_item->getStatusLabel() ?></span>
                <span class="note-list-customer">
                <?php /* @escapeNotVerified */
                echo __('Customer') ?>
                    <?php if ($block->isCustomerNotificationNotApplicable($_item)): ?>
                        <span class="note-list-customer-notapplicable"><?php /* @escapeNotVerified */
                            echo __('Notification Not Applicable') ?></span>
                    <?php elseif ($_item->getIsCustomerNotified()): ?>
                        <span class="note-list-customer-notified"><?php /* @escapeNotVerified */
                            echo __('Notified') ?></span>
                    <?php else: ?>
                        <span class="note-list-customer-not-notified"><?php /* @escapeNotVerified */
                            echo __('Not Notified') ?></span>
                    <?php endif; ?>
            </span>
                <?php if ($_item->getComment()): ?>
                    <div
                        class="note-list-comment"><?php echo $block->escapeHtml($_item->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?></div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>

    <script>
        require(['prototype'], function () {

            if ($('order_status'))$('order_status').update('<?php /* @escapeNotVerified */ echo $block->getOrder()->getStatusLabel() ?>');

        });
    </script>
</div>
