<?php
$saving_account = $block->getSavingStatus();
?>
<?php if($saving_account['used']):?>
<div class="admin__page-section-item-title" style="margin-top: 20px">
    <span class="title"><?=__("Saving account")?></span>
</div>
<div class="admin__page-section-item-content">
    <?=__("Using status : ")?>
    <strong>Yes</strong>

</div>
<div class="admin__page-section-item-content">
    <?=__("Total amount : ")?>
    <strong><?=$saving_account['amount']?></strong>

</div>
<?php endif;?>